<?php

namespace common\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "{{%slider}}".
 *
 * @property int $id
 * @property string|null $caption
 * @property string|null $tom_tat
 * @property string|null $link
 *
 * @property AnhSlider[] $anhSliders
 */
class Slider extends \yii\db\ActiveRecord
{
    public $hinh_anhs;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%slider}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['caption', 'link'], 'string', 'max' => 100],
            [['tom_tat'], 'string', 'max' => 300],
            [['hinh_anhs'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'caption' => 'Tiêu Đề',
            'tom_tat' => 'Tóm Tắt',
            'link' => 'Link',
            'hinh_anhs'=>'Hình ảnh',
        ];
    }

    /**
     * Gets query for [[AnhSliders]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getAnhSliders()
    {
        return $this->hasMany(AnhSlider::className(), ['slider_id' => 'id']);
    }

    public function beforeDelete()
    {
        //beforeDelete->delete()->afterDelete

       // AnhSlider::deleteAll(['slider_id'=>$this->id]); //xoa tren db
        $anh_sliders=AnhSlider::findAll(['slider_id'=>$this->id]); //tim ra tat ca cac anh slider lien quan
        foreach ($anh_sliders as $anhSlider){
            $anhSlider->delete(); // goi ham Delete cua AnhSlider -> beforeDelete+ afterDelete
        }

        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $files=UploadedFile::getInstances($this,'hinh_anhs');
        foreach ($files as $file){
            $ten_file=time().$file->name;

            $anh_siler=new AnhSlider();
            $anh_siler->slider_id=$this->id;
            $anh_siler->file=$ten_file;
            if($anh_siler->save()){
                $path=dirname(dirname(__DIR__)).'/images/'.$ten_file;
                $file->saveAs($path);
            }

        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
